### ISSUE TITLE
composer package

### ISSUE THREAD

**Issue by mgp25** [lazyjsonmapper/lazyjsonmapper#1]
@lazyjsonauthor @SteveJobzniak Hello, you need to update packagist or create a new package to add it to composer.

Regards

**Comment by ghost** [comment]
Hey man, yeah I turned this into an organization and I am preparing to add it to packagist. I think I screwed up by deleting the SteveJobzniak account before I had unlinked my Packagist so I will see if I can recover my Packagist account to move the `lazyjsonmapper/lazyjsonmapper` package to this new location. :-) I think I can do it! I will let you know.

**Comment by ghost** [comment]
@mgp25 Ok I recovered the password. And I am on packagist now with the old SteveJobzniak account. I need to talk to you on Gitter (via this account).
